### ISSUE TITLE
check Einfügen einer zweiten "Schreibtafel"

### ISSUE THREAD

**Issue by DL30** [FoodCoopNahrungskette/foodsoft#10]
Wie aufwendig wäre es, 
eine zweite Tafel auf Startseite nach Log-In einzufügen?
Diese würde für Bestellwünsche an Dienst 6 dienen.

**Comment by hpfmn** [comment]
Klingt erstmal nach einer einfacheren Sache, ich nehm das mal für diesen Monat in mein TODO

**Comment by hpfmn** [comment]
done
