### ISSUE TITLE
Schreiberlaubnis für Dienst 3 auf Basar

### ISSUE THREAD

**Issue by DL30** [FoodCoopNahrungskette/foodsoft#11]
bisher hat Dienst 3 nur Lesezugang

**Comment by hpfmn** [comment]
Auch was für diesen Monat

**Comment by DL30** [comment]
Auch zum Pfandzettel braucht Dienst 3 noch Schreiberlaubnis/-zugang

**Comment by DL30** [comment]
high priority

**Comment by hpfmn** [comment]
done
