### ISSUE TITLE
Zusätzliche Felder in Lieferliste ohne Datenbank-Änderung 

### ISSUE THREAD

**Issue by DL30** [FoodCoopNahrungskette/foodsoft#13]
es sollen in der Lieferliste zusätzliche Teillisten für den User sichtbar sein, 
wie z. B. 
"behaltene Waren, die umbestellt geliefert wurden", 
die in Datenbank einfach zu Hinzufügung in Lieferliste führen.

oder auch
"Reklamierte Nichtlieferung"
hier eingetragene Artikel (oder als auswählbarer Status) werden nicht Lieferliste hinzugefügt/ von dieser gelöscht, aber die Kosten werden dennoch auf Rechnungsbetrag mit Steuer draufgeschlagen.

-> welche Felder/ Funktionen genau, bestimmen wir Ende Juni in einem gemeinsamen Treffen.

High priority
#5

**Comment by hpfmn** [comment]
Wie soll das ohne Datenbank funktionieren? In welchem Status die Produkte sind muss ja irgendwo gespeichert werden.

**Comment by DL30** [comment]
Wir hatten schon telefonisch zu gesprochen, dass es geht. klären wir am nächsten Freitag.

**Comment by hpfmn** [comment]
ich erinnere mich noch, dass wir das besprochen hatten - bin mir aber nicht mehr ganz sicher wie es gemeint war und konnte es jetzt aus der Beschreib hier nicht lesen. Aber im zweifel klären wir das einfach am Freitag.

**Comment by hpfmn** [comment]
wird gelöst in #5
