### ISSUE TITLE
Deposit

### ISSUE THREAD

**Issue by hpfmn** [FoodCoopNahrungskette/foodsoft#2]
check if deposit is also in the .bnn files provided by terra

**Comment by hpfmn** [comment]
Im Terra-Katalog ist in der Excel-Version bei Pfandartikeln ein „p“ als Kennzeichnung.
i. Prüfen, ob auch im bnn-Dateiformat, dass von der Foodsoft eingelesen wird, die Pfandkennzeichnung eingefügt ist.
ii. Prüfen, ob diese als Auslöser eines automatischen Pfandeintrags in dem Produkteintrag genutzt werden kann.
iii. Aufwand abschätzen.
2 b) Automatisierung des Pfandeintrags

**Comment by hpfmn** [comment]
http://www.n-bnn.de/sites/default/dateien/bilder/Downloads/BNN-3-Schnittstelle_01_04_2011.pdf

**Comment by hpfmn** [comment]
So wie es aussieht gibt es nicht ein einfaches "P", sondern es gibt eine Pfandnummer -> sobald die Vorhanden ist sollte es ein Pfandartikel sein. (Siehe BNN Schnittstelle Seite 3: 27 PfandNrLadeneinheit, 28 PfandNrBestelleinheit)
[column_to_number.txt](https://github.com/FoodCoopNahrungskette/foodsoft/files/2064894/column_to_number.txt)


[bnn_as_ods.zip](https://github.com/FoodCoopNahrungskette/foodsoft/files/2064901/bnn_as_ods.zip)

**Comment by hpfmn** [comment]
vermutlich lässt sich aus der Nummer sogar sagen, was für ein Pfand das ist

**Comment by hpfmn** [comment]
Die Terra files sind CP850

**Comment by DL30** [comment]
wie zeitlich aufwändig wäre die Programmierung, damit beim Katalog-Einlesen beim Vorhandensein einer Pfandnummer eine Pfandinfo (bei uns ist Pfand ja stets 16 Cent) in der Foodsoft vermerkt wird?
