### ISSUE TITLE
Add status to item in distribution list

### ISSUE THREAD

**Issue by hpfmn** [FoodCoopNahrungskette/foodsoft#6]
add status option to items in distribution list (like "nicht lieferbar")

**Comment by hpfmn** [comment]
Copare also to #5

**Comment by DL30** [comment]
Hier muss nochmal genau überlegt werden, was genau Ziel der Status-Option ist
 - > würde der Status etwas auslösen? 
z. B. entfernen aus Lieferliste + automatischer Vorschlag für die nächste Bestellvorlage?
Bisher werden nicht lieferbare Artikel einfach aus der Lieferliste gelöscht - was an sich genügt.
Von daher können wir diese Idee womöglich verwerfen.
Ich tausch mich da nochmal zu mit anderen aus.

**Comment by hpfmn** [comment]
wird duch #5 gelöst
